name: 'Crystal Ball Responder'
description: 'Action to react on empty or invalid issue'
author: n0npax
branding:
  icon: 'octagon'  
  color: 'green'

inputs:
  issueNum:
    description: 'number of issue to check'
    required: true
  repoName:
    description: 'repository name'
  labels:
    description: 'labels separated by comma. For example "foo,bar,baz"'
    default: "invalid description"
outputs:
  commented:
    description: 'Was comment added'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.issueNum }}
    - ${{ inputs.repoName }}
    - ${{ inputs.labels }}
