name: crystal_ball
description: A simple github action to respond to new issue
version: 0.1.0-dev
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
#  path: ^1.7.0
  args: ^2.1.0
  logging: ^1.0.1
  github: ^8.1.0

dev_dependencies:
  pedantic: ^1.9.0
