name: crystal_ball
description: A simple tool to respond to new issue (github action core)
version: 0.1.0
homepage: https://github.com/n0npax/crystal-ball
repository: https://github.com/n0npax/crystal-ball

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
#  path: ^1.7.0
  args: ^2.1.0
  logging: ^1.0.1
  github: ^8.1.0


dev_dependencies:
  test: ^1.17.4
  pedantic: ^1.9.0
  cider: ^0.1.0

