name: Dart CI/CD
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.0
      - name: test
        run: |
          pub get
          dart test $(find test -type f) -r expanded
  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.0
      - name: test
        run: |
          pub get
          echo TODO