name: Docker image
on:
  push:
    branches:
      - main
  pull_request: {}
  release:
    types: [published]
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (release)
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/crystal-ball:${{ github.ref }}
            docker.pkg.github.com/${{ github.repository }}/crystal-ball:latest
            docker.pkg.github.com/${{ github.repository }}/crystal-ball:${{ github.sha }}
