name: Docker image
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/crystal-ball:${{ github.sha }}
