name: Docker image (release)
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (release)
        run: |
          docker build -t docker.pkg.github.com/${{ github.repository }}/crystal-ball:${{ steps.get_version.outputs.VERSION }} .
          docker push docker.pkg.github.com/${{ github.repository }}/crystal-ball:${{ steps.get_version.outputs.VERSION }}