name: crystall ball (from Dockerfile)
on:
  issues:
    types: [opened, edited]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Fortune teller
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Crystal Ball
        if: ${{ !github.event.issue.pull_request }}
        uses: ./ 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REXEXP_NO_EMPTY_DESC: 'description:?\s*\Z'
          REGEXP_AT_LEAST_10_WORDS: '(\w+\s+){0,10}'
          #COMMENT_MSG: blah blah blah
        with:
          org: ${{ github.repository_owner }}
          repoName: crystal-ball
          issueNum: "${{ github.event.issue.number }}"
          labels: "foo,bar,baz,qux"
