on:
  push: {}
  pull_request: {}
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        #if: ${{ !github.event.issue.pull_request }}
        uses: ./ 
        id: test
        with:
          issueNum: "${{ github.event.issue.number }}"
      # Use the output from the `hello` step
      #- name: Get the output time
      #  run: echo "The time was ${{ steps.hello.outputs.time }}"