name: crystall ball (from Dockerfile)
on:
  issues:
    types: [opened, edited]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Fortune teller
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Crystal Ball
        if: ${{ !github.event.issue.pull_request }}
        uses: ./ 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CRYSTAL_NOMATCH_REGEX_FOO: '^foo$'
          CRYSTAL_MATCH_REGEX_BAR: 'bar{4}'
          #COMMENT_MSG: blah blah blah
        with:
          org: ${{ github.repository_owner }}
          repoName: crystal-ball
          issueNum: "${{ github.event.issue.number }}"
          labels: "invalid,crystall ball needed"